#!/bin/bash
#curl -X POST http://localhost:8080 -H "Content-Type:application/json"  -d '{"temp":"150", "t":"0.005", "l":"20000", "iso":"100"}'
curl -X POST http://localhost:8080 -H "Content-Type:application/json"  -d '{"t":"0.005", "l":"20000", "iso":"100"}'
